Repository Suraj-kumar00/Flash-Fathom-AI, pull requests merged in 2024-11, with the labels that each got.

#66 Add GitHub Workflow for Auto-Closing Similar Issue Requests
  .github/workflows/detect-duplicate.yml
Labels: enhancement, good first issue, hacktoberfest, gssoc-ext, Level 1

#75 issue with herobackground #74
  src/app/page.tsx
Labels: bug, good first issue, hacktoberfest, gssoc-ext, Level 2

#77 PULL REQUEST CHECKER WORKFLOW AUTOMATION 🚀
  .github/workflows/pr-checker.yml
Labels: enhancement, gssoc-ext, Level 2
