Repository Suraj-kumar00/Flash-Fathom-AI, pull requests merged in 2024-10, with the labels that each got.

#50 fix: Make generate flashcard text button color white in dark mode.
  package.json
  pnpm-lock.yaml
  src/components/ui/button.tsx
Labels: good first issue, hacktoberfest, gssoc-ext, Level 1

#59 fix: Choos plan button text is not visible in the dark mode
  src/app/(auth)/sign-in/[[...sign-in]]/page.tsx
  src/app/(auth)/sign-up/[[...sign-up]]/page.tsx
  src/components/core/flash-card.tsx
  src/components/ui/button.tsx
Labels: hacktoberfest, gssoc-ext, Level 2

#60 fix: Choos plan button text is not visible in the dark mode
  src/app/pricing/page.tsx
Labels: good first issue, hacktoberfest, gssoc-ext, Level 1

#58 Add subscribe
  .env.example
  package.json
  pnpm-lock.yaml
  src/app/api/subscribe/route.ts
  src/app/page.tsx
  src/components/Footer.tsx
  src/components/ui/StayUpdated.tsx
  src/middleware.ts
Labels: enhancement, hacktoberfest, gssoc-ext, Level 3

#64 Fix flashcard responsiveness
  src/components/core/flash-card.tsx
Labels: good first issue, hacktoberfest, gssoc-ext, Level 1
